@echo off
set NG_CLI_ANALYTICS=false
title Lanzando Biblioteca Zen...
cd /d "%~dp0angular-app"
echo Iniciando servidor en segundo plano...
start /min cmd /c "npm start"
echo Esperando a que el sistema armonice (10 segundos)...
timeout /t 10
echo Abriendo tu biblioteca en el navegador...
start http://localhost:4200
exit
